version: '3'
# This is for local dev deployments. It will not grab the latest docker
# image for the django app from the docker repo. It will build and deploy the local
# changes
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb
    networks:
      - tank_yard

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    networks:
      - tank_yard
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
      - "8186:8086"
      - "8188:8080"
    env_file:
      - 'env.grafana'
    networks:
      - tank_yard
    links:
      - influxdb

  yandex-tank:
    build:
      context:  docker/yandex-tank
      dockerfile: Dockerfile
    depends_on:
      - telegraf
    volumes:
      - tank-app:/etc/yandex-tank
    ports:
      - "8888:8888"
    networks:
      - tank_yard

#  controlcenter:
#    build:
#        context:  docker/controlcenter
#        dockerfile: Dockerfile
#    ports:
#      - "8080:80"
#    depends_on:
#      - yandex-tank
#    tmpfs:
#      - /tld_service/var
#    networks:
#      - tank_yard
networks:
  tank_yard:
volumes:
  tank-app: